id: 722be04d-13f2-4c26-ae43-d72ab53a7691
type: application
interactions:
- targetId: 90bd7d8e-039d-4557-b444-c499bd7bea79
  type: service
  level: component
- targetId: 92ff9944-70ae-4b06-af09-670159a7c7a1
  type: domain
  level: component
annotations:
- namespace: c4modeler
  name: position
  value:
    922d60c4-1333-4a2a-b33d-41e378c04fb4:
      x: 140
      y: 124.5
name: NewApplication
description: Description for NewApplication
baseApiUrl: ca/baseapi
