id: 922d60c4-1333-4a2a-b33d-41e378c04fb4
type: web-application
interactions:
- targetId: e0a76742-f4c0-49b2-bf0e-9701007f5907
  type: gateway
  level: container
annotations:
- namespace: c4modeler
  name: position
  value:
    4ac04730-176c-4743-8bcd-fd1e46f07bd7:
      x: 435.5896302250804
      y: 124.2154379596281
- namespace: c4modeler
  name: boundary
  value:
    x: 140
    y: 375.5
    width: 280
    height: 751
prefix: app
author: CodeArchitects
target: angular@19
architecture: single-page-application
strict: false
name: NewWebApplication
description: Description for NewWebApplication
children:
- id: 722be04d-13f2-4c26-ae43-d72ab53a7691
  type: application
- id: 92ff9944-70ae-4b06-af09-670159a7c7a1
  type: domain
- id: 99d61fc6-4215-4fc5-88f0-fc4fbbbe8845
  type: scenario
